$_CONF['db_report']['host'] = '34.126.83.225';
$_CONF['db_report']['port'] = '3306';
$_CONF['db_report']['user'] = 'dashboard';
$_CONF['db_report']['pass'] = '-pPIqstwDJHz';
$_CONF['db_report']['name'] = 'dashboard_report';

db: dashboard_report_vinamilk
user: dashboard_report_vinamilk
pass: 6vtRhNxa79zPsfs5

In [1]:
import mysql.connector

# Establish connection
conn = mysql.connector.connect(
    host="10.0.0.3",
    port = '3306',
    user="dashboard_report_vinamilk",
    password="6vtRhNxa79zPsfs5",
    database="dashboard_report_vinamilk"
)

# Create a cursor object
cursor = conn.cursor()

# Execute a simple query
cursor.execute("SHOW TABLES")

# Fetch results
for table in cursor.fetchall():
    print(table)

# Close connection
cursor.close()
conn.close()

('facebook_creative',)
('facebook_device_daily_raw',)
('facebook_performance_daily_raw',)
('facebook_platform_daily_raw',)
('googleads_creative',)
('googleads_device_report5',)
('googleads_performance_daily_raw_v1',)
('googleads_placement_report5',)
('report_campaign_creative',)
('report_campaign_digital_3platform',)
('report_campaign_digital_facebook',)
('report_campaign_digital_tiktok',)
('report_campaign_digital_youtube',)
('report_campaign_plan_file',)
('report_mtm_facebook',)
('report_mtm_spending_total',)
('report_mtm_tiktok',)
('report_mtm_youtube',)
('tiktok_creative_preview',)
('tiktok_creative_preview_tmp',)
('tiktok_report10',)
('tiktok_template_5',)

In [2]:
import mysql.connector
import pandas as pd

try:
    # Establish MySQL connection
    conn = mysql.connector.connect(
        host="10.0.0.3",
        port = '3306',
        user="dashboard_report_vinamilk",
        password="6vtRhNxa79zPsfs5",
        database="dashboard_report_vinamilk"
    )

    print("Connected to MySQL successfully!")

    # Create a cursor and execute the query
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM report_campaign_plan_file")

    # Fetch column names
    column_names = [desc[0] for desc in cursor.description]

    # Fetch all rows and convert to DataFrame
    rows = cursor.fetchall()
    df = pd.DataFrame(rows, columns=column_names)
    

except mysql.connector.Error as err:
    print(f"Error: {err}")

finally:
    if 'cursor' in locals():
        cursor.close()
    if 'conn' in locals() and conn.is_connected():
        conn.close()
        print("MySQL connection closed.")

Connected to MySQL successfully!
MySQL connection closed.

In [4]:
df.head()

,Funnel,Start Date,End Date,Objective,Region,Platform,Buying Type,Ad format,Placement,TA,...,click_estimate,frequency_estimate,frequency_estimate_week,frequency_combine_estimate_week,er_estimate,vtr_estimate,ctr_estimate,click to rate(CTR),So tuan,Ngay
0,AWARENESS,22/01,31/01,Reach,HCM,Youtube,YT For Reach,Video 15s,Auction instream/infeed/shorts,F25-44,...,1.620,2,None,None,None,"15,0%","0,1%","2,0",10,None
1,AWARENESS,22/01,31/01,Reach,HCM,Youtube,YT For Reach,Video 15s,Auction instream/infeed/shorts,P18-24,...,814.000,2,None,None,None,"15,0%","0,1%","2,0",10,None
2,AWARENESS,22/01,31/01,Reach,HCM,Youtube,YT Non Skip,Video 15s,Auction instream/infeed/shorts,F25-44,...,1.215,2,None,None,None,"85,0%","0,1%","2,0",10,None
3,AWARENESS,22/01,31/01,Reach,HCM,Youtube,YT Non Skip,Video 15s,Auction instream/infeed/shorts,P18-24,...,610.000,2,None,None,None,"85,0%","0,1%","2,0",10,None
4,AWARENESS,22/01,31/01,Reach,HCM,Facebook,FB R&F,"Still image, multi, Video 15s, 6s, social pos...",Facebook/ Instagram Newsfeed; Facebook/ Instag...,F25-44,...,2.640,2,None,None,None,"3,0%","0,1%","2,0",10,None

In [5]:
df.Placement.unique()

array(['Auction  instream/infeed/shorts',
       'Facebook/ Instagram Newsfeed; Facebook/ Instagram Story;',
       'Selected OTT app list', 'Auction  instream/\ninfeed/shorts',
       'Selected sitelist', 'RON- contextual kw related to Probi topic',
       'In feed ad on Tiktok', 'Transport Saver', 'Google search', None],
      dtype=object)

In [18]:
import mysql.connector
import pandas as pd
from sqlalchemy import create_engine
df_tt = pd.read_csv('/Users/khanhvx/Documents/Work/SC/VNM/Campaign report/SAMPLE DATA - TT2.csv')
df_gg = pd.read_csv('/Users/khanhvx/Documents/Work/SC/VNM/Campaign report/SAMPLE DATA - GG2.csv')
df_fb = pd.read_csv('/Users/khanhvx/Documents/Work/SC/VNM/Campaign report/SAMPLE DATA - FB2.csv')


df_tt.head()

,Day,Campaign Name,Ad Group Name,Campaign ID,Ad Group ID,Ad Name,Ad ID,Cost,Impressions,Clicks,...,Brand Name,Campaign Name.1,Camp Type,Buying Type,Buying Model,Placement,Start Date,End Date,Ad Format,Post Name
0,2025-02-11,2025_TIKTOK_BRANDING_SCUMS_PROBI_SUSTAIN-Q1_Vi...,OptVIEW_SAVED_P_18-24_Urban_RTG-Viewer_Infeed,1821946631226386,1823540245293089,other_KOL-Bác sĩ Huy_spark-ads,"1,82354E+15",1984510.0,168016.0,465.0,...,PROBI,SUSTAIN-Q1,View,AUCTION,CPV,In-feed,27/01/2025,31/01/2025,other,spark-ads
1,2025-02-13,2025_TIKTOK_BRANDING_SCUMS_PROBI_SUSTAIN-Q1_Vi...,OptVIEW_SAVED_F_25-44_Urban_RTG-Viewer_Infeed-...,1821946485699602,1823956006137905,other_KOL-Bác sĩ Huy_spark-ads,1823956008374338,10632.0,666.0,3.0,...,PROBI,SUSTAIN-Q1,View,AUCTION,CPV,In-feed,27/01/2025,31/01/2025,other,spark-ads
2,2025-02-18,2025_TIKTOK_BRANDING_SCUMS_PROBI_SUSTAIN-Q1_Vi...,OptVIEW_SAVED_P_18-24_Urban_RTG-Viewer_Infeed,1821946631226386,1823540245293089,other_KOL-Bác sĩ Huy_spark-ads,"1,82354E+15",0.0,0.0,0.0,...,PROBI,SUSTAIN-Q1,View,AUCTION,CPV,In-feed,27/01/2025,31/01/2025,other,spark-ads
3,2025-02-02,2025_TIKTOK_BRANDING_SCUMS_PROBI_SUSTAIN-Q1_Vi...,OptVIEW_SAVED_F_25-44_Rural_Affinity_Infeed,1821946962617361,1822106410989602,other_KOL-Bác sĩ Huy_spark-ads,1822322083347474,1010562.0,75463.0,345.0,...,PROBI,SUSTAIN-Q1,View,AUCTION,CPV,In-feed,27/01/2025,31/01/2025,other,spark-ads
4,2025-02-16,2025_TIKTOK_BRANDING_SCUMS_PROBI_SUSTAIN-Q1_Vi...,OptVIEW_SAVED_P_18-24_HCM_RTG-Viewer_Infeed,1821945570551889,1823540493350913,other_KOL-Bác sĩ Huy_spark-ads,1823540493351953,410612.0,12572.0,35.0,...,PROBI,SUSTAIN-Q1,View,AUCTION,CPV,In-feed,27/01/2025,31/01/2025,other,spark-ads

# đồng bộ column

In [72]:
df_total.columns

Index(['day', 'campaign name', 'ad group name', 'campaign id', 'ad group id',
       'ad name', 'ad id', 'cost', 'impressions', 'clicks', 'reach',
       'conversion', 'view 2s3s', 'view 6strue viewthruplays',
       'video views at 25', 'video views at 50', 'video views at 75',
       'video views at 100', 'paid follows', 'paid likes', 'comments',
       'shares', 'profile visits', 'account currency', 'engagement',
       'platfrom', 'funnel', 'format', 'kpis', 'region', 'demo', 'creative',
       'platform', 'objective', 'category', 'brand name', 'campaign name1',
       'camp type', 'buying type', 'buying model', 'placement', 'start date',
       'end date', 'ad format', 'post name', 'engagements', 'views',
       'video played to 25', 'video played to 50', 'video played to 75',
       'video played to 100', 'currency', 'cost (usd)', 'exchange rate',
       'ad set name', 'ad set id', 'frequency', 'link clicks',
       'post engagement', 'cost per result', 'results', 'video watches at 25',
       'video watches at 50', 'video watches at 75', 'video watches at 100',
       'messaging conversations started'],
      dtype='object')

In [82]:
df_fb.rename(columns={
    "3-Second Video Views": "View 2s 3s",
    "ThruPlays": "View 6s True view Thruplays",
    "post engagement": "engagement",
    "video watches at 25": "Video Views at 25",
    "video watches at 50": "Video Views at 50",
    "video watches at 75": "Video Views at 75",
    "video watches at 100": "Video Views at 100",
    "Link Clicks": "Clicks"
}, inplace=True)

df_tt.rename(columns={
    "2-Second Video Views": "View 2s 3s",
    "6-Second Video Views": "View 6s True view Thruplays"
}, inplace=True)

In [79]:
df_fb.columns

Index(['Day', 'Campaign Name', 'Ad Set Name', 'Ad Name', 'Campaign Id',
       'Ad Set Id', 'Ad Id', 'Reach', 'Frequency', 'Impressions',
       'Link Clicks', 'Engagement', 'Cost Per Result', 'Results', 'Cost',
       'View 2S3S', 'Video Views At 25', 'Video Views At 50',
       'Video Views At 75', 'Video Views At 100', 'View 6Strue Viewthruplays',
       'Messaging Conversations Started', 'Platfrom', 'Format', 'Kpis',
       'Region', 'Demo', 'Creative', 'Platform', 'Funnel', 'Objective',
       'Category', 'Brand Name', 'Campaign Name1', 'Camp Type', 'Buying Type',
       'Buying Model', 'Placement', 'Start Date', 'End Date', 'Ad Format',
       'Post Name'],
      dtype='object')

In [83]:
df_tt.columns = df_tt.columns.str.lower()
df_fb.columns = df_fb.columns.str.lower()
df_gg.columns = df_gg.columns.str.lower()

df_tt.columns = df_tt.columns.str.replace(r'[%./]', '', regex=True).str.title()
df_fb.columns = df_fb.columns.str.replace(r'[%./]', '', regex=True).str.title()
df_gg.columns = df_gg.columns.str.replace(r'[%./]', '', regex=True).str.title()

df_tt.columns = df_tt.columns.str.replace(r'[%./]', '', regex=True)
df_fb.columns = df_fb.columns.str.replace(r'[%./]', '', regex=True)
df_gg.columns = df_gg.columns.str.replace(r'[%./]', '', regex=True)

In [34]:
# Assuming exchange rate is already available in the dataset or defined separately
df_gg["Exchange Rate"] = 25000  # Replace with actual exchange rate

# Calculate Cost in VND
df_gg["Cost"] = df_gg["Cost (USD)"] * df_gg["Exchange Rate"]

# Format TA to Pxx-xx Fxx-xx

In [32]:
import re

# Update Demo column in df_tt
df_tt["Demo"] = df_tt["Demo"].str.replace(r'^PP(\d{2})-(\d{2})$', r'P\1-\2', regex=True)
df_tt["Demo"] = df_tt["Demo"].str.replace(r'^FM(\d{2})-(\d{2})$', r'F\1-\2', regex=True)

# Update Demo column in df_gg
df_gg["Demo"] = df_gg["Demo"].str.replace(r'^P(\d{4})$', lambda m: f'P{m.group(1)[:2]}-{m.group(1)[2:]}', regex=True)
df_gg["Demo"] = df_gg["Demo"].str.replace(r'^F(\d{4})$', lambda m: f'F{m.group(1)[:2]}-{m.group(1)[2:]}', regex=True)

df_tt.Demo.value_counts()

Demo
F25-44    145
P18-24    121
Name: count, dtype: int64

In [84]:
df_total = pd.concat([df_tt, df_gg, df_fb], ignore_index=True)

In [85]:
df_total.columns = df_total.columns.str.replace(r'[%\.]', '', regex=True)

In [86]:
df_total.head()

,Day,Campaign Name,Ad Group Name,Campaign Id,Ad Group Id,Ad Name,Ad Id,Cost,Impressions,Clicks,...,Video Played To 100,Currency,Cost (Usd),Exchange Rate,Ad Set Name,Ad Set Id,Frequency,Cost Per Result,Results,Messaging Conversations Started
0,2025-02-11,2025_TIKTOK_BRANDING_SCUMS_PROBI_SUSTAIN-Q1_Vi...,OptVIEW_SAVED_P_18-24_Urban_RTG-Viewer_Infeed,1821946631226386,1823540245293089,other_KOL-Bác sĩ Huy_spark-ads,"1,82354E+15",1984510.0,168016.0,465.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-02-13,2025_TIKTOK_BRANDING_SCUMS_PROBI_SUSTAIN-Q1_Vi...,OptVIEW_SAVED_F_25-44_Urban_RTG-Viewer_Infeed-...,1821946485699602,1823956006137905,other_KOL-Bác sĩ Huy_spark-ads,1823956008374338,10632.0,666.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-02-18,2025_TIKTOK_BRANDING_SCUMS_PROBI_SUSTAIN-Q1_Vi...,OptVIEW_SAVED_P_18-24_Urban_RTG-Viewer_Infeed,1821946631226386,1823540245293089,other_KOL-Bác sĩ Huy_spark-ads,"1,82354E+15",0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-02-02,2025_TIKTOK_BRANDING_SCUMS_PROBI_SUSTAIN-Q1_Vi...,OptVIEW_SAVED_F_25-44_Rural_Affinity_Infeed,1821946962617361,1822106410989602,other_KOL-Bác sĩ Huy_spark-ads,1822322083347474,1010562.0,75463.0,345.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-02-16,2025_TIKTOK_BRANDING_SCUMS_PROBI_SUSTAIN-Q1_Vi...,OptVIEW_SAVED_P_18-24_HCM_RTG-Viewer_Infeed,1821945570551889,1823540493350913,other_KOL-Bác sĩ Huy_spark-ads,1823540493351953,410612.0,12572.0,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# File plan

In [90]:
df_plan = pd.read_csv('/Users/khanhvx/Documents/Work/SC/VNM/Campaign report/plan.csv')

In [91]:
df_plan.rename(columns={"%reach_estimate": "reach_percent_estimate", 
                      "%reach_combine_estimate": "reach_combine_percent_estimate"}, inplace=True)

In [92]:
df_plan.head()

,Funnel,Start Date,End Date,Objective,Region,Platform,Buying Type,Ad format,Placement,TA,...,click_estimate,frequency_estimate,frequency_estimate_week,frequency_combine_estimate_week,er_estimate,vtr_estimate,ctr_estimate,click to rate(CTR),So tuan,Ngay
0,AWARENESS,22/01,31/01,Reach,HCM,Youtube,YT For Reach,Video 15s,Auction instream/infeed/shorts,F25-44,...,1.620,2,NaN,NaN,NaN,"15,0%","0,1%","2,0",10,NaN
1,AWARENESS,22/01,31/01,Reach,HCM,Youtube,YT For Reach,Video 15s,Auction instream/infeed/shorts,P18-24,...,814.000,2,NaN,NaN,NaN,"15,0%","0,1%","2,0",10,NaN
2,AWARENESS,22/01,31/01,Reach,HCM,Youtube,YT Non Skip,Video 15s,Auction instream/infeed/shorts,F25-44,...,1.215,2,NaN,NaN,NaN,"85,0%","0,1%","2,0",10,NaN
3,AWARENESS,22/01,31/01,Reach,HCM,Youtube,YT Non Skip,Video 15s,Auction instream/infeed/shorts,P18-24,...,610.000,2,NaN,NaN,NaN,"85,0%","0,1%","2,0",10,NaN
4,AWARENESS,22/01,31/01,Reach,HCM,Facebook,FB R&F,"Still image, multi, Video 15s, 6s, social pos...",Facebook/ Instagram Newsfeed; Facebook/ Instag...,F25-44,...,2.640,2,NaN,NaN,NaN,"3,0%","0,1%","2,0",10,NaN

# Tạo file làm creative report

In [101]:
df_creative = df_total.groupby(["Creative", "Funnel", "Platform", "Format", "Demo", "Region", "Day", "Start Date", "End Date"]).agg({
    "Impressions": "sum",
    "Reach": "sum",
    "View 2S3S": "sum",
    "View 6Strue Viewthruplays": "sum",
    "Video Views At 25": "sum",
    "Video Views At 50": "sum",
    "Video Views At 75": "sum",
    "Video Views At 100": "sum",
    "Clicks": "sum",
    "Engagement": "sum",
    "Cost": "sum",
    "Views": "sum"
}).reset_index()

df_creative.head()

,Creative,Funnel,Platform,Format,Demo,Region,Day,Start Date,End Date,Impressions,...,View 2S3S,View 6Strue Viewthruplays,Video Views At 25,Video Views At 50,Video Views At 75,Video Views At 100,Clicks,Engagement,Cost,Views
0,Chess,Awareness,FACEBOOK,In-feed,F25-44,HCM,2025-01-24,24/01/2025,31/01/2025,29171.0,...,2159.0,216.0,1633.0,639.0,342.0,194.0,9.0,2170.0,291120.0,0.0
1,Chess,Awareness,FACEBOOK,In-feed,F25-44,HCM,2025-01-25,24/01/2025,31/01/2025,28045.0,...,2129.0,216.0,1638.0,629.0,331.0,202.0,11.0,2144.0,279891.0,0.0
2,Chess,Awareness,FACEBOOK,In-feed,F25-44,HCM,2025-01-26,24/01/2025,31/01/2025,29550.0,...,2354.0,261.0,1788.0,688.0,367.0,235.0,8.0,2366.0,294911.0,0.0
3,Chess,Awareness,FACEBOOK,In-feed,F25-44,HCM,2025-01-27,24/01/2025,31/01/2025,38033.0,...,3235.0,358.0,2490.0,994.0,547.0,338.0,16.0,3252.0,379569.0,0.0
4,Chess,Awareness,FACEBOOK,In-feed,F25-44,HCM,2025-01-28,24/01/2025,31/01/2025,40620.0,...,3480.0,357.0,2687.0,1065.0,575.0,339.0,14.0,3496.0,405383.0,0.0

In [102]:
df_creative.to_excel('/Users/khanhvx/Documents/Work/SC/VNM/Campaign report/creative.xlsx')

In [103]:
df_creative["Creative"] = df_creative["Creative"].str.replace("Bác sĩ", "Bác sỹ", regex=True)

In [44]:
df_total['Format'].value_counts()

Format
In-feed      738
In-stream    243
Reels        175
Name: count, dtype: int64

The if_exists parameter in df.to_sql() has three options:
	1.	'fail' (default) – Raises an error if the table already exists.
	2.	'replace' – Drops the existing table and creates a new one.
	3.	'append' – Adds new rows to the existing table without deleting old data.

Example Usage:

df.to_sql('table_name', engine, if_exists='replace', index=False)  # Replaces table
df.to_sql('table_name', engine, if_exists='append', index=False)   # Appends data
df.to_sql('table_name', engine, if_exists='fail', index=False)     # Raises an error if the table exists

In [ ]:
df_total.head()

In [ ]:
from sqlalchemy import create_engine
import pandas as pd

DB_TYPE = 'mysql'  # Change to 'postgresql' for PostgreSQL
DB_HOST = '10.0.0.3'
DB_PORT = '3306'  # Change for different databases
DB_USER = 'dashboard_report_vinamilk'
DB_PASS = '6vtRhNxa79zPsfs5'
DB_NAME = 'dashboard_report_vinamilk'

try:
    conn = mysql.connector.connect(
        host=DB_HOST,
        user=DB_USER,
        password=DB_PASS,
        database=DB_NAME,
        charset="utf8mb4"
    )
    
    if conn.is_connected():
        cursor = conn.cursor()
        print("Connected to MySQL successfully!")
    else:
        print("Failed to connect.")

except mysql.connector.Error as e:
    print(f"Error: {e}")

# Create SQLAlchemy engine
cursor = conn.cursor()
cursor.execute("SET NAMES utf8mb4;")
cursor.execute("SET CHARACTER SET utf8mb4;")
engine = create_engine(f"mysql+pymysql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}")

def upload_to_mysql(df, table_name, engine, if_exists='append'):
    """
    Uploads a DataFrame to a MySQL table.
    
    :param df: Pandas DataFrame to upload
    :param table_name: Name of the table in the database
    :param engine: SQLAlchemy engine object
    :param if_exists: What to do if the table already exists ('fail', 'replace', 'append')
    """
    try:
        # Upload DataFrame to MySQL
        df.to_sql(table_name, engine, if_exists=if_exists, index=False)
        
        print(f"Data successfully uploaded to {table_name}!")
    except Exception as e:
        print(f"Error uploading data to {table_name}: {e}")

# Example usage:
# engine = create_engine(f"mysql+pymysql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}")
# upload_to_mysql(df_tt, 'report_campaign_digital_tiktok', engine)

Connected to MySQL successfully!

In [93]:
upload_to_mysql(df_tt, 'report_campaign_digital_tiktok', engine)
upload_to_mysql(df_gg, 'report_campaign_digital_youtube', engine)
upload_to_mysql(df_fb, 'report_campaign_digital_facebook', engine)
upload_to_mysql(df_total, 'report_campaign_digital_3platform', engine)
upload_to_mysql(df_creative, 'report_campaign_creative', engine)
upload_to_mysql(df_plan, 'report_campaign_plan_file', engine)

Data successfully uploaded to report_campaign_digital_tiktok!
Data successfully uploaded to report_campaign_digital_youtube!
Data successfully uploaded to report_campaign_digital_facebook!
Data successfully uploaded to report_campaign_digital_3platform!
Data successfully uploaded to report_campaign_creative!
Data successfully uploaded to report_campaign_plan_file!

In [105]:
upload_to_mysql(df_creative, 'report_campaign_creative', engine)

Data successfully uploaded to report_campaign_creative!

In [ ]:
df_plan.columns[df_plan.columns.duplicated()]

In [89]:
df_plan.head()

,Funnel,Start Date,End Date,Objective,Region,Platform,Buying Type,Ad format,Placement,TA,...,click_estimate,frequency_estimate,frequency_estimate_week,frequency_combine_estimate_week,er_estimate,vtr_estimate,ctr_estimate,click to rate(CTR),So tuan,Ngay
0,AWARENESS,22/01,31/01,Reach,HCM,Youtube,YT For Reach,Video 15s,Auction instream/infeed/shorts,F25-44,...,1.620,2,NaN,NaN,NaN,"15,0%","0,1%","2,0",10,NaN
1,AWARENESS,22/01,31/01,Reach,HCM,Youtube,YT For Reach,Video 15s,Auction instream/infeed/shorts,P18-24,...,814.000,2,NaN,NaN,NaN,"15,0%","0,1%","2,0",10,NaN
2,AWARENESS,22/01,31/01,Reach,HCM,Youtube,YT Non Skip,Video 15s,Auction instream/infeed/shorts,F25-44,...,1.215,2,NaN,NaN,NaN,"85,0%","0,1%","2,0",10,NaN
3,AWARENESS,22/01,31/01,Reach,HCM,Youtube,YT Non Skip,Video 15s,Auction instream/infeed/shorts,P18-24,...,610.000,2,NaN,NaN,NaN,"85,0%","0,1%","2,0",10,NaN
4,AWARENESS,22/01,31/01,Reach,HCM,Facebook,FB R&F,"Still image, multi, Video 15s, 6s, social pos...",Facebook/ Instagram Newsfeed; Facebook/ Instag...,F25-44,...,2.640,2,NaN,NaN,NaN,"3,0%","0,1%","2,0",10,NaN

In [106]:
df_creative.to_excel('/Users/khanhvx/Documents/Work/SC/VNM/Campaign report/creative.xlsx')

In [107]:
df_plan.to_excel('/Users/khanhvx/Documents/Work/SC/VNM/Campaign report/plan.xlsx')

In [108]:
df_region= df_total.groupby(["Region", "Funnel", "Platform", "Format", "Demo", "Day", "Start Date", "End Date"]).agg({
    "Impressions": "sum",
    "Reach": "sum",
    "View 2S3S": "sum",
    "View 6Strue Viewthruplays": "sum",
    "Video Views At 25": "sum",
    "Video Views At 50": "sum",
    "Video Views At 75": "sum",
    "Video Views At 100": "sum",
    "Clicks": "sum",
    "Engagement": "sum",
    "Cost": "sum",
    "Views": "sum"
}).reset_index()

df_region.head()

,Region,Funnel,Platform,Format,Demo,Day,Start Date,End Date,Impressions,Reach,View 2S3S,View 6Strue Viewthruplays,Video Views At 25,Video Views At 50,Video Views At 75,Video Views At 100,Clicks,Engagement,Cost,Views
0,HCM,Awareness,FACEBOOK,In-feed,F25-44,2025-01-24,24/01/2025,31/01/2025,348094.0,281871.0,26469.0,2817.0,19754.0,7618.0,4198.0,2686.0,161.0,26661.0,3473948.0,0.0
1,HCM,Awareness,FACEBOOK,In-feed,F25-44,2025-01-25,24/01/2025,31/01/2025,320422.0,292273.0,25866.0,2689.0,19346.0,7459.0,3993.0,2568.0,151.0,26053.0,3197818.0,0.0
2,HCM,Awareness,FACEBOOK,In-feed,F25-44,2025-01-26,24/01/2025,31/01/2025,378948.0,343388.0,33674.0,3510.0,25239.0,10000.0,5356.0,3334.0,152.0,33871.0,3781907.0,0.0
3,HCM,Awareness,FACEBOOK,In-feed,F25-44,2025-01-27,24/01/2025,31/01/2025,436871.0,397078.0,41545.0,4226.0,31709.0,12991.0,6752.0,4027.0,222.0,41815.0,4359955.0,0.0
4,HCM,Awareness,FACEBOOK,In-feed,F25-44,2025-01-28,24/01/2025,31/01/2025,380555.0,353432.0,38285.0,4051.0,29349.0,12314.0,6358.0,3855.0,185.0,38512.0,3797960.0,0.0

In [110]:
df_region_test= df_total.groupby(["Region", "Funnel", "Platform", "Format", "Demo"]).agg({
    "Cost": "sum",
    "Views": "sum"
}).reset_index()

df_region_test.head()

  Region     Funnel  Platform     Format    Demo        Cost  Views
0    HCM  Awareness  FACEBOOK    In-feed  F25-44  54594817.0    0.0
1    HCM  Awareness  FACEBOOK    In-feed  P18-24  49921092.0    0.0
2    HCM  Awareness  FACEBOOK      Reels  F25-44   4886779.0    0.0
3    HCM  Awareness  FACEBOOK      Reels  P18-24   4660783.0    0.0
4    HCM  Awareness    GOOGLE  In-stream  F25-44   8480250.0    0.0